// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsIAxQ4zuHhopgM-JDylDYSfhZBy2eak4',
    appId: '1:252111377436:web:037a5c5fa179f0b1d07bd9',
    messagingSenderId: '252111377436',
    projectId: 'tagref-3601e',
    authDomain: 'tagref-3601e.firebaseapp.com',
    storageBucket: 'tagref-3601e.appspot.com',
    measurementId: 'G-8NTN5WH97Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYPZGCOMFLkIsCDf8r8MG-FcbriavrVZg',
    appId: '1:252111377436:android:637cb29165d9f7a4d07bd9',
    messagingSenderId: '252111377436',
    projectId: 'tagref-3601e',
    storageBucket: 'tagref-3601e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfoJlicHrXR7mugLuaLt18nedUFNsj6I8',
    appId: '1:252111377436:ios:28585c2e51b8d98fd07bd9',
    messagingSenderId: '252111377436',
    projectId: 'tagref-3601e',
    storageBucket: 'tagref-3601e.appspot.com',
    iosClientId: '252111377436-r2odt5rlrqs7a2qgv1mqbr5m47s03scp.apps.googleusercontent.com',
    iosBundleId: 'com.tagref.tagref',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfoJlicHrXR7mugLuaLt18nedUFNsj6I8',
    appId: '1:252111377436:ios:28585c2e51b8d98fd07bd9',
    messagingSenderId: '252111377436',
    projectId: 'tagref-3601e',
    storageBucket: 'tagref-3601e.appspot.com',
    iosClientId: '252111377436-r2odt5rlrqs7a2qgv1mqbr5m47s03scp.apps.googleusercontent.com',
    iosBundleId: 'com.tagref.tagref',
  );
}
